Sprint 3/step 1
Artemii-Kravtsov/react-burger pull request #5
Opened 2023-06-18 13:50 UTC by Artemii-Kravtsov

2023-06-18 16:26 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Реализована защита роутов
- Есть обновление токена
- Настроены все редиректы

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- В payload PATCH запроса ничего не попадает, поэтому данные юзера невозможно изменить на странице профиля

- Чтобы приходящий с сервера токен заносился всегда по пути "/" в куку, нужно в функцию setCookies передавать как значение параметра props аргумент {path="/"}:
setCookie('name', value, { path: '/' }).
Об этом можно прочитать здесь: https://learn.javascript.ru/cookie
Уничтожать токен при логауте пользователя нужно также по пути path: '/'.
В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

<img width="572" alt="Снимок экрана 2023-06-18 в 19 19 18" src="https://github.com/Artemii-Kravtsov/react-burger/assets/60173362/f7e896f7-3ff7-4c59-832d-2d44e89ea25d">

- Обновление токена не работает. При ошибке `jwt expired` не срабатывает обновление. Можете попробовать изменить токен в хранилище и тогда вы получите ошибку `invalid signature` - можете попробовать на неё отработать обновление.

Для обновления можете  использовать обертку над fetch, примерно такую

```
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};

const fetchWithRefresh = async (url, options) => {
  try {
    const res = await fetch(url, options); //делаем запрос
    return await checkReponse(res);
  } catch (err) {
    if (err.message === "jwt expired") {
      const refreshData = await refreshToken(); //обновляем токен
      localStorage.setItem("refreshToken", refreshData.refreshToken);
      localStorage.setItem("accessToken", refreshData.accessToken); //(или в cookies)
      options.headers.authorization = refreshData.accessToken;
      const res = await fetch(url, options); //вызываем перезапрос данных
      return await checkReponse(res);
    } else {
      return Promise.reject(err);
    }
  }
};
```

- Если есть инпуты, то они должны быть внутри тега form, и на этот тег form нужно навешивать обработчик onSubmit, а не обработчик onClick на кнопку сабмита.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-06-18 19:52 UTC, Artemii-Kravtsov commented
1. Исправил, теперь PATCH работает норм. Возвращалось 200 - думал, что проблемка на беке
2. Теперь сохраняю куки в корень. Статья огонь!
3. Исправил, теперь токен обновляется. Спасибо за то, что подсказал как дебажить
4. Изменил тип кнопок на страницах с полями, добавил события onReset и onSubmit

2023-06-19 13:14 UTC, andryxxa93 commented
**Необходимо исправить**
- Теперь всё отлично, но есть одна проблема. Изменяя данные юзера в payload запроса уходит поле password с "зашифрованным" паролем  в виде `*********`. И получается, что даже не меняя пароль - он всё равно меняется и юзер этого не увидит, поэтому не сможет зайти в свой аккаунт. В идеальном варианте в запрос должно уходить только то поле, которое изменилось.

<img width="527" alt="Снимок экрана 2023-06-19 в 16 12 17" src="https://github.com/Artemii-Kravtsov/react-burger/assets/60173362/100c0282-b37f-4b8c-84a3-ed766a3304e4">

2023-06-19 19:02 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-06-19 22:06 UTC, merged