Sprint 5/step 1
Artemii-Kravtsov/react-burger pull request #7
Opened 2023-07-12 19:15 UTC by Artemii-Kravtsov

2023-07-12 20:34 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Реализован универсальный веб-сокет
- Сокеты открываются и закрываются согласно брифу
- Хорошая типизация проекта

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.


**Необходимо исправить**
- Не правильно определяется день когда был осуществлён заказ - всегда показывает "Сегодня".

<img width="1440" alt="Снимок экрана 2023-07-12 в 23 29 37" src="https://github.com/Artemii-Kravtsov/react-burger/assets/60173362/b2884dbd-cee0-48cf-ace7-0bf6bc770ffc">

- Следует избавиться от any в конструкциях `    const dispatch: any = useDispatch()`
- В некоторых местах используется не типизированный useSelector
<img width="590" alt="Снимок экрана 2023-07-12 в 23 32 11" src="https://github.com/Artemii-Kravtsov/react-burger/assets/60173362/77e32cd9-2e6c-4278-9150-8d2250dc66a0">

Более подробно описание проблемы смотрите комментарии в pull request.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-07-12 20:34 UTC, andryxxa93 commented on src/services/middlewares/socketMiddleware.ts
> +            socket.onmessage = event => {
**Можно лучше**
Необходимо добавить проверку при получении сообщения от сокета. Eсли токен протух и приходит поле message 'Invalid or missing token' то его необходимо обновить через refreshToken.

2023-07-12 22:04 UTC, Artemii-Kravtsov commented
Здравствуйте! Спасибо за ревью!

Насчёт обработки протухшего токена - 
1) докинул в обработчик onclose, а не onerror (пишут, что у события onerror нет атрибута с сообщением https://stackoverflow.com/questions/18803971/websocket-onerror-how-to-read-error-description)
2) попытался потестировать, но не смог дождаться, когда сервер закроет сокет из-за протухшего токена. мне почему-то казалось, что проверка токена происходит один раз в момент сокетного подключения, разве не так?

2023-07-13 06:23 UTC, andryxxa93 commented
> Здравствуйте! Спасибо за ревью!
> 
> Насчёт обработки протухшего токена -
> 
> 1. докинул в обработчик onclose, а не onerror (пишут, что у события onerror нет атрибута с сообщением https://stackoverflow.com/questions/18803971/websocket-onerror-how-to-read-error-description)
> 2. попытался потестировать, но не смог дождаться, когда сервер закроет сокет из-за протухшего токена. мне почему-то казалось, что проверка токена происходит один раз в момент сокетного подключения, разве не так?

Проверку надо было сделать внутри события onmessage 😊

2023-07-13 06:23 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-07-13 08:02 UTC, merged